/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CambiosYDevolucionesRouteImport } from './routes/cambios-y-devoluciones'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAdminProductosRouteImport } from './routes/_admin.admin.productos'
import { Route as AdminAdminPedidosRouteImport } from './routes/_admin.admin.pedidos'
import { Route as AdminAdminMensajesRouteImport } from './routes/_admin.admin.mensajes'
import { Route as AdminAdminConfiguracionRouteImport } from './routes/_admin.admin.configuracion'
import { Route as AdminAdminProductosNuevoRouteImport } from './routes/_admin.admin.productos.nuevo'
import { Route as AdminAdminProductosIdRouteImport } from './routes/_admin.admin.productos.$id'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiosYDevolucionesRoute = CambiosYDevolucionesRouteImport.update({
  id: '/cambios-y-devoluciones',
  path: '/cambios-y-devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProductosRoute = AdminAdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPedidosRoute = AdminAdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMensajesRoute = AdminAdminMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminConfiguracionRoute = AdminAdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminProductosNuevoRoute =
  AdminAdminProductosNuevoRouteImport.update({
    id: '/nuevo',
    path: '/nuevo',
    getParentRoute: () => AdminAdminProductosRoute,
  } as any)
const AdminAdminProductosIdRoute = AdminAdminProductosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminProductosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cambios-y-devoluciones': typeof CambiosYDevolucionesRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/faqs': typeof FaqsRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/configuracion': typeof AdminAdminConfiguracionRoute
  '/admin/mensajes': typeof AdminAdminMensajesRoute
  '/admin/pedidos': typeof AdminAdminPedidosRoute
  '/admin/productos': typeof AdminAdminProductosRouteWithChildren
  '/admin/productos/$id': typeof AdminAdminProductosIdRoute
  '/admin/productos/nuevo': typeof AdminAdminProductosNuevoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cambios-y-devoluciones': typeof CambiosYDevolucionesRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/faqs': typeof FaqsRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/configuracion': typeof AdminAdminConfiguracionRoute
  '/admin/mensajes': typeof AdminAdminMensajesRoute
  '/admin/pedidos': typeof AdminAdminPedidosRoute
  '/admin/productos': typeof AdminAdminProductosRouteWithChildren
  '/admin/productos/$id': typeof AdminAdminProductosIdRoute
  '/admin/productos/nuevo': typeof AdminAdminProductosNuevoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/cambios-y-devoluciones': typeof CambiosYDevolucionesRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/faqs': typeof FaqsRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/producto/$slug': typeof ProductoSlugRoute
  '/_admin/admin/configuracion': typeof AdminAdminConfiguracionRoute
  '/_admin/admin/mensajes': typeof AdminAdminMensajesRoute
  '/_admin/admin/pedidos': typeof AdminAdminPedidosRoute
  '/_admin/admin/productos': typeof AdminAdminProductosRouteWithChildren
  '/_admin/admin/productos/$id': typeof AdminAdminProductosIdRoute
  '/_admin/admin/productos/nuevo': typeof AdminAdminProductosNuevoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cambios-y-devoluciones'
    | '/carrito'
    | '/catalogo'
    | '/contacto'
    | '/faqs'
    | '/favoritos'
    | '/login'
    | '/privacidad'
    | '/registro'
    | '/terminos'
    | '/admin'
    | '/producto/$slug'
    | '/admin/configuracion'
    | '/admin/mensajes'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/productos/$id'
    | '/admin/productos/nuevo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cambios-y-devoluciones'
    | '/carrito'
    | '/catalogo'
    | '/contacto'
    | '/faqs'
    | '/favoritos'
    | '/login'
    | '/privacidad'
    | '/registro'
    | '/terminos'
    | '/admin'
    | '/producto/$slug'
    | '/admin/configuracion'
    | '/admin/mensajes'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/productos/$id'
    | '/admin/productos/nuevo'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/cambios-y-devoluciones'
    | '/carrito'
    | '/catalogo'
    | '/contacto'
    | '/faqs'
    | '/favoritos'
    | '/login'
    | '/privacidad'
    | '/registro'
    | '/terminos'
    | '/_admin/admin'
    | '/producto/$slug'
    | '/_admin/admin/configuracion'
    | '/_admin/admin/mensajes'
    | '/_admin/admin/pedidos'
    | '/_admin/admin/productos'
    | '/_admin/admin/productos/$id'
    | '/_admin/admin/productos/nuevo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CambiosYDevolucionesRoute: typeof CambiosYDevolucionesRoute
  CarritoRoute: typeof CarritoRoute
  CatalogoRoute: typeof CatalogoRoute
  ContactoRoute: typeof ContactoRoute
  FaqsRoute: typeof FaqsRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RegistroRoute: typeof RegistroRoute
  TerminosRoute: typeof TerminosRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambios-y-devoluciones': {
      id: '/cambios-y-devoluciones'
      path: '/cambios-y-devoluciones'
      fullPath: '/cambios-y-devoluciones'
      preLoaderRoute: typeof CambiosYDevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/productos': {
      id: '/_admin/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminAdminProductosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/pedidos': {
      id: '/_admin/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminAdminPedidosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/mensajes': {
      id: '/_admin/admin/mensajes'
      path: '/mensajes'
      fullPath: '/admin/mensajes'
      preLoaderRoute: typeof AdminAdminMensajesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/configuracion': {
      id: '/_admin/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminAdminConfiguracionRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/productos/nuevo': {
      id: '/_admin/admin/productos/nuevo'
      path: '/nuevo'
      fullPath: '/admin/productos/nuevo'
      preLoaderRoute: typeof AdminAdminProductosNuevoRouteImport
      parentRoute: typeof AdminAdminProductosRoute
    }
    '/_admin/admin/productos/$id': {
      id: '/_admin/admin/productos/$id'
      path: '/$id'
      fullPath: '/admin/productos/$id'
      preLoaderRoute: typeof AdminAdminProductosIdRouteImport
      parentRoute: typeof AdminAdminProductosRoute
    }
  }
}

interface AdminAdminProductosRouteChildren {
  AdminAdminProductosIdRoute: typeof AdminAdminProductosIdRoute
  AdminAdminProductosNuevoRoute: typeof AdminAdminProductosNuevoRoute
}

const AdminAdminProductosRouteChildren: AdminAdminProductosRouteChildren = {
  AdminAdminProductosIdRoute: AdminAdminProductosIdRoute,
  AdminAdminProductosNuevoRoute: AdminAdminProductosNuevoRoute,
}

const AdminAdminProductosRouteWithChildren =
  AdminAdminProductosRoute._addFileChildren(AdminAdminProductosRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminConfiguracionRoute: typeof AdminAdminConfiguracionRoute
  AdminAdminMensajesRoute: typeof AdminAdminMensajesRoute
  AdminAdminPedidosRoute: typeof AdminAdminPedidosRoute
  AdminAdminProductosRoute: typeof AdminAdminProductosRouteWithChildren
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminConfiguracionRoute: AdminAdminConfiguracionRoute,
  AdminAdminMensajesRoute: AdminAdminMensajesRoute,
  AdminAdminPedidosRoute: AdminAdminPedidosRoute,
  AdminAdminProductosRoute: AdminAdminProductosRouteWithChildren,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CambiosYDevolucionesRoute: CambiosYDevolucionesRoute,
  CarritoRoute: CarritoRoute,
  CatalogoRoute: CatalogoRoute,
  ContactoRoute: ContactoRoute,
  FaqsRoute: FaqsRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  PrivacidadRoute: PrivacidadRoute,
  RegistroRoute: RegistroRoute,
  TerminosRoute: TerminosRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
